<h4><?php echo $this->__('Module List') ?></h4>

<br><h4><?php echo $this->__('Table 1'); ?></h4> 

<?php $model = $this->showTable('test'); ?>

<table border='3' style='width:100%;' class="data-table" id="my-orders-table">
   <tr>
       <th>Id</th>
       <th>Title</th>
       <th>Content</th>
       <th>Status</th>
       <th>Edit</th>
       <th>Delete</th>
   </tr>
<?php foreach ($model as $item) { ?>
    <tr>
        <td> <?php echo $item->getData('test_id'); ?></td>
        <td> <?php echo $item->getData('title'); ?></td>
        <td> <?php echo $item->getData('content'); ?></td>
        <td><?php if($item->getData('status')==1){ echo $this->__('Enabled');} else { echo $this->__('Disabled');} ?></td>
        <td><a href="<?php echo $this->getEditUrl('test',$item->getData('test_id')) ?>" class="f-left"><?php echo $this->__('Edit') ?></a></td>
        <td><a href="<?php echo $this->getDeleteUrl('test',$item->getData('test_id')) ?>" class="f-left"><?php echo $this->__('Delete') ?></a></td>
    </tr>

<?php } ?>
</table>

<?php echo "<br><br><h4><a href=".$this->getAddUrl('test').">".$this->__('Add Row')."</a></h4>"; ?>